version: '3.8'

services:
  web:
    build: .
    container_name: server1_backend
    restart: always
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
      - ./logs:/app/logs
    environment:
      - DJANGO_SETTINGS_MODULE=nerdslab.settings
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-False}
    expose:
      - 8000
    networks:
      - auth_network

  nginx:
    image: nginx:alpine
    container_name: auth_service_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./staticfiles:/usr/share/nginx/html/static:ro
      - ./media:/usr/share/nginx/html/media:ro
      - ./nginx/logs:/var/log/nginx
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - web
    networks:
      - auth_network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  backup:
    image: alpine:latest
    volumes:
      - .:/app
      - ./backups:/app/backups
    command: >
      /bin/sh -c "
        apk add --no-cache sqlite bash findutils gzip;
        echo '0 2 * * * /app/scripts/backup_sqlite.sh' > /etc/crontabs/root;
        crond -f -l 2
      "
    restart: unless-stopped
    networks:
      - auth_network

networks:
  auth_network:
    name: nerdslab_auth_network