# Generated by Django 4.2.7 on 2025-05-05 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_account_locked_until_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlabprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userlabprogress',
            name='user_lab',
        ),
        migrations.DeleteModel(
            name='UserLab',
        ),
        migrations.DeleteModel(
            name='UserLabProgress',
        ),
    ]
